baseurl = "http://videotek.github.io/"
languageCode = "ru"
title = "Мосохрана VideoTek"
theme = "hugo-creative-theme"
canonifyurls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Мосохрана VideoTek"
	description = "Your description"


	# Navigation
	[params.navigation]
		brand = "Мосохрана VideoTek"
		phone = "+7 (495) 971-39-56"

		[params.navigation.links]
			about     = "О Нас"
			services  = "Услуги"
			portfolio = "Типы объектов"
			contact   = "Контакты"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Ваши комфорт и безопасность - наша работа!"
		subtitle   = "Установка цифровых систем видеонаблюдения в Москве и московской области."
		buttonText = "узнать подробности"


	# About section
	[params.about]
		headline    = "Мы предоставляем полный комплекс услуг по проектированию, установке, обслуживанию слаботочных систем."
		description = "Видеонаблюдение, Охранная сигнализация, Пожарная сигнализация, Система контроля и управления доступом, Структурированная кабельная сеть, Телефония, Озвучивание помещений"
		buttonText  = "Услуги!"


	# Service section
	[params.services]
		headline = "Наши услуги"

        [[params.services.list]]
            icon = "fa-video-camera"
            title = "Видеонаблюдение"
            description = "проектирование, установка и обслуживание систем видеонаблюдения всех типов"

        [[params.services.list]]
			icon = "fa-user-secret"
			title = "Охранная сигнализация"
			description = "проектирование, установка и обслуживание охранных систем различных типов"

		[[params.services.list]]
            icon = "fa-fire"
            title = "Пожарная сигнализация"
            description = "проектирование, установка и обслуживание пожарных сигнализаций"

#        [[params.services.list]]
#            icon = "fa-heart"
#            title = "Собутыльник"
#            description = "Собутыльник с высшим образованием, знаток анекдотов и интеллектуал. Материалы заказчика. Оплата почасовая. Дорого! (интим не предлагать)"

        [[params.services.list]]
            icon = "fa-random"
            title = "СКС"
            description = "проектирование кабельной системы, расчет оптимальной конфигурации кабельной сети, прокладка кабельных трасс, подключение кабельных компонентов"

        [[params.services.list]]
            icon = "fa-phone"
            title = "Телефония, 3G / 4G LTE интернет"
            description = "установка и настройка цифровых телефонных станций, усилителей сотовой связи, 4G LTE / 3G Wi-Fi роутеров"

        [[params.services.list]]
            icon = "fa-lock"
            title = "СКУД"
            description = "установка и обслуживание систем контроля и управления доступом"

#        [[params.services.list]]
#            icon = "fa-compress"
#            title = "Интернет"
#            description = "Мобильный и кабельный интернет. Дома и на даче!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Клиент"
        date = "Дата"
        category = "Категория"
        buttonText = "Закрыть"
		price     = "Цена"

    # Aside section
	[params.aside]
		headline = "Некоторые расценки на наши услуги"

		[params.aside.button]
			text = "Скачать"
			link = "/price.pdf"

	# Contact section
	[params.contact]
		headline = "Свяжитесь с нами!"
		description = "Готовы начать Ваш следующий проект с нами? Отлично! Позвоните нам или напишите по электронной почте. Мы ответим так быстро, как только сможем!"
		phone = "+7 (495) 971-39-56, +7 (926) 990-88-59"
		email = "videotek@mosohrana.ru"

    # About section
	[params.why]
		title = "Почему с нами выгодно"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Станьте частью нашей истории!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.why.events]]
			icon = "certificate"
			icontype = "success"
			title = "Большой опыт"
			description = "Работаем в области систем безопасности более 12 лет."

		[[params.why.events]]
			icon = "road"
			icontype = "success"
			title = "Бесплатный выезд"
			description = "Приедем на ваш объект для оценки в течение 24х часов."

		[[params.why.events]]
			icon = "thumbs-up"
			icontype = "success"
			title = "Гарантия"
			description = "Предоставляем гарантию 24 месяца на выполненные работы."

		[[params.why.events]]
			icon = "hourglass"
			icontype = "success"
			title = "Соблюдаем сроки"
			description = "Сдаем объект вовремя, независимо от его размеров и сложности."

		[[params.why.events]]
			icon = "user"
			icontype = "success"
			title = "Персональный менеджер"
			description = "Будет сопровождать вас на всех этапах работ."

		[[params.why.events]]
			icon = "usd"
			icontype = "success"
			title = "Гибкая система платежей"
			description = "При необходимости разобьем оплату на удобные вам этапы."

